name: ScrollingSigns
authors: [stuntguy3000, kreashenz]
version: 1.2.2
main: me.stuntguy3000.scrollingsigns.SSPlugin
commands:
    scrollingsigns:
        description: Main command for ScrollingSigns
        aliases: [ss]