name: ScrollingSigns
author: stuntguy3000
version: 0.2
main: me.stuntguy3000.scrollingsigns.SSPlugin
commands:
    scrollingsign:
        description: Main command for ScrollingSigns
        aliases: [ss]